import type { Metadata } from 'next';

import './globals.css';
import Header from '@/components/Header';

import AOSInitializer from '@/components/AosInitializer';

import { Montserrat } from 'next/font/google';
import { UserProvider } from '../../context/userContext';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'] // Adjust weights as needed
});

export const metadata: Metadata = {
  title: 'Raja Ongkir',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <UserProvider>
          <Header />
          <AOSInitializer />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
